# Default values for carbon-aware-sdk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: kube-system

image:
  name: carbon-aware-sdk
  repository: ghcr.io/green-software-foundation/carbon-aware-sdk
  pullPolicy: IfNotPresent
  tag: "0.1.0"
  auth:
    username: username
    password: password
    
service:
  type: ClusterIP
  port: 80

rbac:
  clusterRoleName: carbon-aware-binding
  serviceAccountName: carbon-aware-sa
  roleRef: cluster-admin

nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
