# This is an example of an Azure DevOps pipeline
# that builds GSF.CarbonAware nuget package using the existing script (scripts/package/create_packages.sh) and publish it internally.

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  csproj: 'src/GSF.CarbonAware/src/GSF.CarbonAware.csproj'
  buildConfiguration: 'Release'
  ArtifactNuGetName: 'packages-nuget'
  packageDir: '$(Build.ArtifactStagingDirectory)/packages/nuget'
 
steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 6.x
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: '$(csproj)'

- task: Bash@3
  displayName: 'Run script'
  inputs:
    targetType: 'filePath'
    filePath: "$(System.DefaultWorkingDirectory)/scripts/package/create_packages.sh"
    arguments: >
      $(csproj) $(packageDir)
   
- publish: '$(packageDir)'
  displayName: 'Publish Artifact: $(ArtifactNuGetName)'
  artifact: 'packages-nuget'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))



